# Generated by Django 2.1 on 2019-02-03 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_report', '0002_report_reported_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='reported_by',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
