# Generated by Django 2.1 on 2019-02-04 12:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('add_report', '0003_auto_20190203_0139'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='punish',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
