# Generated by Django 2.1 on 2019-02-03 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='reported_by',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
